# Generated by Django 5.1.5 on 2025-02-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Fornecedor')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdg_produto', models.CharField(max_length=13, unique=True, verbose_name='Código do Produto')),
                ('nm_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('desc_produto', models.TextField(blank=True, null=True, verbose_name='Descrição do Produto')),
                ('preco_venda_produto', models.FloatField(verbose_name='Preço de Venda')),
                ('preco_compra_produto', models.FloatField(blank=True, null=True, verbose_name='Preço de Compra')),
                ('margem_lucro_produto', models.FloatField(blank=True, null=True, verbose_name='Margem de Lucro (%)')),
                ('fabricante_produto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fabricante do Produto')),
                ('lt_produto', models.CharField(blank=True, max_length=13, null=True, verbose_name='Lote do Produto')),
                ('dt_fbr_produto', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fabricação do Produto')),
                ('dt_val_produto', models.DateTimeField(blank=True, null=True, verbose_name='Data de Validade do Produto')),
                ('ativo_produto', models.BooleanField(default=True, verbose_name='Produto Ativo')),
                ('img_produto', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto')),
                ('md_produto', models.CharField(choices=[('unidade', 'Unidade'), ('quilo', 'Quilo'), ('litro', 'Litro'), ('metro', 'Metro')], default='unidade', max_length=10, verbose_name='Unidade de Medida')),
                ('ps_liquido_produto', models.FloatField(blank=True, null=True, verbose_name='Peso Líquido (kg)')),
                ('ps_bruto_produto', models.FloatField(blank=True, null=True, verbose_name='Peso Bruto (kg)')),
                ('ctg_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoria')),
                ('fornecedor_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_estoque', models.FloatField(verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.FloatField(default=0, verbose_name='Estoque Mínimo')),
                ('dt_entrada_estoque', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada no Estoque')),
                ('dt_atualiza_estoque', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização do Estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'db_table': 'estoque',
            },
        ),
    ]
