# Generated by Django 5.1.5 on 2025-02-03 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('cpf_cliente', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Cliente')),
                ('mtd_pagamento', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cheque', 'Cheque')], max_length=10)),
                ('parcelas', models.PositiveSmallIntegerField(choices=[(1, '1x'), (2, '2x'), (3, '3x'), (4, '4x'), (5, '5x'), (6, '6x')], verbose_name='Parcelas')),
                ('total', models.FloatField(default=0, verbose_name='Valor Total')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'venda',
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_venda_produto', models.FloatField(verbose_name='Quantidade')),
                ('preco_unitario', models.FloatField(verbose_name='Preço Unitário')),
                ('subtotal', models.FloatField(editable=False, verbose_name='Subtotal')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='venda.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
                'db_table': 'item_venda',
            },
        ),
    ]
